name: Run-Minitest

on:
  push:
    branches:
      - main
    paths:
      - "**.rb"
      - ".github/workflows/minitest.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**.rb"
      - ".github/workflows/minitest.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - name: Run test
      run: |
        bundle install
        bundle exec rake test
